name: Run Action on Check Suite Completion

on:
  check_suite:
    types: [completed]

jobs:
  on_success:
    runs-on: ubuntu-latest
    steps:
      - name: Do something when all checks pass
        run: |
          echo "All checks have passed!"
          # Aquí puedes agregar los comandos que quieres ejecutar
          # después de que todos los checks hayan pasado
