name: Run Action on Check Suite Completion

on:
  check_suite:
    types: [completed]

jobs:
  on_success:
    runs-on: ubuntu-latest
    if: github.event.check_suite.conclusion == 'success'
    steps:
      - name: Do something when all checks pass
        run: |
          echo "All checks have passed!"
          # Aquí puedes agregar los comandos que quieres ejecutar
          # después de que todos los checks hayan pasado

  on_failure:
    runs-on: ubuntu-latest
    if: github.event.check_suite.conclusion != 'success'
    steps:
      - name: Do something when some checks fail
        run: |
          echo "Some checks have failed or were cancelled!"