name: Run Action on Commit Status Change

on:
  status: {}

jobs:
  on_status:
    runs-on: ubuntu-latest
    steps:
      - name: Print status information
        run: |
          echo "Commit SHA: ${{ github.sha }}"
          echo "Context: ${{ github.event.context }}"
          echo "State: ${{ github.event.state }}"
          echo "Target URL: ${{ github.event.target_url }}"