name: Example Passed Workflow

on:
  push:
    branches:
      - main

jobs:
  success_job:
    runs-on: ubuntu-latest

    steps:
      - name: Echo a message
        run: echo "This workflow will always pass!"